### ISSUE TITLE
Can't install multiple apks from external file picker

### ISSUE THREAD

**Issue by sanatsathaye** [Aefyr/SAI#126]
If I tap and hold multiple files and then click open, SAI attempts to install an "Unknown app" and then installs nothing due to failing to parse Android Manifest error.

**Comment by Aefyr** [comment]
Is Pro mode disabled?

**Comment by sanatsathaye** [comment]
It seems legacy external and Pro mode external file picker are different? That's confusing... Well using Pro mode's external picker I can't install a single apk as well and not just multiple. It fails with `/proc/self/fd/48 (Permission denied)` and then asks if I want to install them anyway, and if I do that it fails with `Failure [INSTALL_FAILED_INVALID_APK: No packages staged]`. When I tried with multiple, nothing happens at all except it saying that customisation is not possible. This is the logcat I got during installing multiple APKs:

```
<<< log_count = 15 >>>
[04-20 01:00:32.092 1229:1229 W/SessionManager]
SessionManager.beginSession():53 Try to begin an already begun session [INPUT_SESSION], end it first

[04-20 01:00:34.462 1229:1229 W/SessionManager]
SessionManager.beginSession():53 Try to begin an already begun session [INPUT_SESSION], end it first

[04-20 01:00:37.532 1229:1229 W/SessionManager]
SessionManager.beginSession():53 Try to begin an already begun session [INPUT_SESSION], end it first

[04-20 01:00:37.992 13969:17489 W/StorageManager]
fallocate() not supported; falling back to ftruncate()

[04-20 01:00:40.616 1229:1229 W/SessionManager]
SessionManager.beginSession():53 Try to begin an already begun session [INPUT_SESSION], end it first

[04-20 01:00:40.820 17108:17497 W/DefaultMessResolver]
Exception while resolving split meta
java.io.FileNotFoundException: /proc/self/fd/40 (Permission denied)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:235)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
	at com.aefyr.sai.installerx.resolver.meta.impl.ZipFileApkSourceFile.nextEntry(ZipFileApkSourceFile.java:34)
	at com.aefyr.sai.installerx.resolver.meta.impl.DefaultSplitApkSourceMetaResolver.parseViaParsingManifests(DefaultSplitApkSourceMetaResolver.java:91)
	at com.aefyr.sai.installerx.resolver.meta.impl.DefaultSplitApkSourceMetaResolver.resolveFor(DefaultSplitApkSourceMetaResolver.java:68)
	at com.aefyr.sai.installerx.resolver.urimess.impl.DefaultUriMessResolver.resolve(DefaultUriMessResolver.java:59)
	at com.aefyr.sai.viewmodels.InstallerXDialogViewModel$LoadMetaTask.doWork(InstallerXDialogViewModel.java:210)
	at com.aefyr.sai.viewmodels.InstallerXDialogViewModel$LoadMetaTask.doWork(InstallerXDialogViewModel.java:193)
	at com.aefyr.sai.utils.SimpleAsyncTask.lambda$execute$2$SimpleAsyncTask(SimpleAsyncTask.java:45)
	at com.aefyr.sai.utils.-$$Lambda$SimpleAsyncTask$SWzOfHeRyN0ZHbFan1oifpiV6Fc.run(Unknown Source:2)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
	Suppressed: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
		at com.aefyr.sai.utils.IOUtils.closeSilently(IOUtils.java:104)
		at com.aefyr.sai.installerx.resolver.meta.impl.ZipFileApkSourceFile.close(ZipFileApkSourceFile.java:58)
		at com.aefyr.sai.installerx.resolver.meta.impl.DefaultSplitApkSourceMetaResolver.parseViaParsingManifests(DefaultSplitApkSourceMetaResolver.java:257)
		... 11 more

[04-20 01:00:40.822 1229:1229 W/SessionManager]
SessionManager.beginSession():53 Try to begin an already begun session [INPUT_SESSION], end it first

[04-20 01:00:40.836 17108:17497 W/DefaultMessResolver]
Exception while resolving split meta
java.io.FileNotFoundException: /proc/self/fd/42 (Permission denied)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:235)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
	at com.aefyr.sai.installerx.resolver.meta.impl.ZipFileApkSourceFile.nextEntry(ZipFileApkSourceFile.java:34)
	at com.aefyr.sai.installerx.resolver.meta.impl.DefaultSplitApkSourceMetaResolver.parseViaParsingManifests(DefaultSplitApkSourceMetaResolver.java:91)
	at com.aefyr.sai.installerx.resolver.meta.impl.DefaultSplitApkSourceMetaResolver.resolveFor(DefaultSplitApkSourceMetaResolver.java:68)
	at com.aefyr.sai.installerx.resolver.urimess.impl.DefaultUriMessResolver.resolve(DefaultUriMessResolver.java:59)
	at com.aefyr.sai.viewmodels.InstallerXDialogViewModel$LoadMetaTask.doWork(InstallerXDialogViewModel.java:210)
	at com.aefyr.sai.viewmodels.InstallerXDialogViewModel$LoadMetaTask.doWork(InstallerXDialogViewModel.java:193)
	at com.aefyr.sai.utils.SimpleAsyncTask.lambda$execute$2$SimpleAsyncTask(SimpleAsyncTask.java:45)
	at com.aefyr.sai.utils.-$$Lambda$SimpleAsyncTask$SWzOfHeRyN0ZHbFan1oifpiV6Fc.run(Unknown Source:2)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
	Suppressed: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
		at com.aefyr.sai.utils.IOUtils.closeSilently(IOUtils.java:104)
		at com.aefyr.sai.installerx.resolver.meta.impl.ZipFileApkSourceFile.close(ZipFileApkSourceFile.java:58)
		at com.aefyr.sai.installerx.resolver.meta.impl.DefaultSplitApkSourceMetaResolver.parseViaParsingManifests(DefaultSplitApkSourceMetaResolver.java:257)
		... 11 more

[04-20 01:00:42.582 1229:1229 W/SessionManager]
SessionManager.beginSession():53 Try to begin an already begun session [INPUT_SESSION], end it first

[04-20 01:00:43.129 462:477 W/BroadcastQueue]
Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver

[04-20 01:00:43.130 462:477 W/BroadcastQueue]
Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver

[04-20 01:00:48.140 462:474 W/ActivityManager]
No permission grants found for com.google.android.apps.photos

[04-20 01:00:48.200 462:1261 W/ActivityManager]
No permission grants found for com.google.android.apps.photos

[04-20 01:00:48.223 462:2199 W/ActivityManager]
No permission grants found for com.google.android.apps.photos

[04-20 01:00:48.273 462:1461 W/ActivityManager]
No permission grants found for com.google.android.apps.photos
```

**Comment by Aefyr** [comment]
> It seems legacy external and Pro mode external file picker are different? That's confusing...

Yes, without Pro mode if multiple files selected via system filepicker, it assumes those are .apk files of the same package. In Pro mode all .apk files are assumed to be of the same package and .apks/.xapk/.zip files are installed separately

> Pro mode's external picker I can't install a single apk as well and not just multiple.

Yeah, there was a bug that broke installation of files that were not parsed. It's fixed in https://github.com/Aefyr/SAI/commit/eb4afb61042ed76247b55f196ccaa5a078f0a637

> When I tried with multiple, nothing happens at all except it saying that customisation is not possible.

There was another bug that caused that, that I've just fixed in https://github.com/Aefyr/SAI/commit/0fd6465d52e11a6b3f46ac0ac16ee13b40c5a877

> It fails with `/proc/self/fd/48 (Permission denied)`

Do you use Android 6 by chance? I think there's a bug with Documents app (aka system filepicker) there that causes that error. I'm not sure that only Android 6 is affected, but I haven't seen reports for other versions yet.


Anyway, here's a debug build of SAI built from https://github.com/Aefyr/SAI/commit/0fd6465d52e11a6b3f46ac0ac16ee13b40c5a877: [app-fdroid-debug.zip](https://github.com/Aefyr/SAI/files/4500164/app-fdroid-debug.zip)
Can you please test the following things with it?
1. If a single file picked via system filepicker installs even though it wasn't parsed
2. If multiple files picked via system filepicker install (assuming they weren't parsed as well because of that permissions error)

Also can you try selecting files via a 3rd party file manager that includes a DocumentsProvider such as Solid Explorer (by opening navigation drawer in system filepicker and selecting it there to pick files with it) to see if that resolves the permissions error?

**Comment by sanatsathaye** [comment]
> Do you use Android 6 by chance?

Android 8.1 :) although this doesn't happen in my Android 9 phone so maybe something has been fixed in there?

> If a single file picked via system filepicker installs even though it wasn't parsed
It still tells me I have the `/proc` error, but if I install anyway it works fine.

> If multiple files picked via system filepicker install (assuming they weren't parsed as well because of that permissions error)
Logcat shows `/proc` error as before but again, installs fine.

> Also can you try selecting a file via a 3rd party file manager
This works on the old version of the app.

I did find a couple of other bugs while investigating the issue.

1. I choose an app to install from SAI. Android asks if I want to allow SAI to install unknown apps, but if I click on Cancel then SAI is just stuck on "Installing" for the app.

2. SAI decided that an exported apks was not valid... Not sure why. It's working now though. App in question was FotMob from the Play Store. I will create a new issue if I can replicate this easily.

**Comment by Aefyr** [comment]
> Android 8.1 :) although this doesn't happen on my Android 9 phone so maybe something has been fixed in there?

I don't know really, it works on Android 7 emulator, maybe it has more to do with the ROM rather than Android version.

> It still tells me I have the `/proc` error, but if I install anyway it works fine.

> Logcat shows `/proc` error as before but again, installs fine.

Thanks for confirming that.

> This works on the old version of the app.

Sorry, does that mean SAI 3.10 can parse a file selected via a 3rd party file manager?

> 1. I choose an app to install from SAI. Android asks if I want to allow SAI to install unknown apps, but if I click on Cancel then SAI is just stuck on "Installing" for the app.

I don't think this can be fixed in SAI, seems like a bug similar to #125.

> 2\. SAI decided that an exported apks was not valid... Not sure why. It's working now though. App in question was FotMob from the Play Store. I will create a new issue if I can replicate this easily.

Not sure what you mean by not valid, but there's a small chance it might have become corrupted since SAI streams backups directly to the target file.

**Comment by Aefyr** [comment]
> I don't know really, it works on Android 7 emulator, maybe it has more to do with the ROM rather than Android version.

Nevermind, it doesn't.

**Comment by sanatsathaye** [comment]
> Sorry, does that mean SAI 3.10 can parse a file selected via a 3rd party file manager?

Yes.

> Not sure what you mean by not valid

Not a valid zip file according to SAI.
