### ISSUE TITLE
failed to allocate

### ISSUE THREAD

**Issue by RainerZufall187** [Aefyr/SAI#271]
it says that it is installing the apks file for ~1 min and then

```
java.io.IOException: Failed to allocate 1837701151 because only 1057042432 allocatable
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.os.ParcelableException.readFromParcel(ParcelableException.java:56)
	at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:82)
	at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:79)
	at android.os.Parcel.readParcelable(Parcel.java:3334)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2421)
	at android.os.Parcel.createException(Parcel.java:2410)
	at android.os.Parcel.readException(Parcel.java:2393)
	at android.os.Parcel.readException(Parcel.java:2335)
	at android.content.pm.IPackageInstallerSession$Stub$Proxy.openWrite(IPackageInstallerSession.java:595)
	at android.content.pm.PackageInstaller$Session.openWrite(PackageInstaller.java:1029)
	at com.aefyr.sai.installer2.impl.rootless.RootlessSaiPackageInstaller.install(RootlessSaiPackageInstaller.java:94)
	at com.aefyr.sai.installer2.impl.rootless.RootlessSaiPackageInstaller.lambda$enqueueSession$0$RootlessSaiPackageInstaller(RootlessSaiPackageInstaller.java:70)
	at com.aefyr.sai.installer2.impl.rootless.-$$Lambda$RootlessSaiPackageInstaller$ivyAcunEgIkYlu_dB2vN6MOWZPU.run(Unknown Source:6)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.os.RemoteException: Remote stack trace:
	at android.util.ExceptionUtils.wrap(ExceptionUtils.java:34)
	at com.android.server.pm.PackageInstallerSession.openWrite(PackageInstallerSession.java:1484)
	at android.content.pm.IPackageInstallerSession$Stub.onTransact(IPackageInstallerSession.java:277)
	at android.os.Binder.execTransactInternal(Binder.java:1185)
	at android.os.Binder.execTransact(Binder.java:1149)
```

yes
apks file is 1,86 gb

![Screenshot_2023-02-15-18-51-22-024_com.cpuid.cpu_z.jpg](https://user-images.githubusercontent.com/40537673/219112016-48e44aa2-6334-4f64-845b-b853742aadeb.jpg)

![Screenshot_2023-02-15-18-52-23-735_com.android.settings.jpg](https://user-images.githubusercontent.com/40537673/219112296-c96d6e47-cf28-4c22-b4f8-d345d99edfc9.jpg)

**Comment by RainerZufall187** [comment]
what now???? 😭😭😭😭😭

**Comment by stanleylhs** [comment]
This app is dead, use the APKmirror app from Play store.

Also if you have root, remove the temp split from SAI in /data/app/
