### ISSUE TITLE
Installation of split apks does not work

### ISSUE THREAD

**Issue by godfuture** [Aefyr/SAI#3]
Many issues when trying to install split apks. I downloaded https://play.google.com/store/apps/details?id=com.simplemobiletools.gallery.pro and selected all required files. Failed with many different errors. Tried root and non-root.

Is this app meant to work on version 1.18?

**Comment by Aefyr** [comment]
What error do you get with rooted installer? A screenshot of the popup with error log will do.

**Comment by godfuture** [comment]
I have been busy these days. I will try again and upload my findings soon.

**Comment by Aefyr** [comment]
abandoned

**Comment by godfuture** [comment]
Trying to install LinkedIn 125000 NY selecting all files related to linkedIn and getting this:


Rooted installer error:

 Device: bq Aquaris X5 Plus | Not MIUI | Android 7.1.2 | Using SignerApkSource ApkSource implementation | SAI 2.1

java.lang.IllegalStateException: No successful match so far
	at java.util.regex.Matcher.ensureMatch(Matcher.java:1051)
	at java.util.regex.Matcher.group(Matcher.java:342)
	at com.aefyr.sai.installer.rooted.RootedSAIPackageInstaller.installApkFiles(RootedSAIPackageInstaller.java:84)
	at com.aefyr.sai.installer.SAIPackageInstaller.lambda$processQueue$0$SAIPackageInstaller(SAIPackageInstaller.java:90)
	at com.aefyr.sai.installer.-$$Lambda$SAIPackageInstaller$6hKMtxaB1Yqc0HYKOE26UUOnkTo.run(lambda)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

**Comment by Aefyr** [comment]
Bad pm binary, if rootless method doesn't work as well, most likely a bad ROM
