### ISSUE TITLE
Rooted method fails : "Error: must specify a APK size"

### ISSUE THREAD

**Issue by nooriro** [Aefyr/SAI#44]
## Environment
- Google Pixel 3 XL, Android 10 (QP1A.191005.007)
- Magisk 20.0
- Split APKs Installer (SAI) 2.8 from Google Play Store

## Steps to reproduce
- Download `netflix-7.30.0-b10-34524_20191009.zip`
  - https://androidfilehost.com/?fid=1899786940962608683
  - **Netflix 7.30.0 build 10 34524 (stock, not modded)**
  - **Contains 2 ABIs, 3 DPIs, and 74 languages** of split APKs :smile: 
- Run SAI, go to **Settings** and set '**Installer**' to '**Rooted (requires root)**'
- Push [Install APKs], check `netflix-7.30.0-b10-34524_20191009.zip` and push [Select (1)]

## Expected Result
- App should be installed instantly.
- **The app is installed successfully with rootless(default) method in SAI.**

## Actual Result
- SAI is not responding for 3-4 minutes, and '**App not installed**' error message pops up as follows :
```
Rooted installer error:

 Device: google Pixel 3 XL | Not MIUI | Android 10 | Using ZipApkSource ApkSource implementation | SAI 2.8

java.lang.RuntimeException: Command: pm install-write -S -1 508953431 0.apk
Exit code: -1
Out:

=============
Err:
Error: must specify a APK size


<!> SAI SuShell Java exception: java.io.IOException: write failed: EPIPE (Broken pipe)
	at libcore.io.IoBridge.write(IoBridge.java:544)
	at java.io.FileOutputStream.write(FileOutputStream.java:392)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:126)
	at com.aefyr.sai.utils.IOUtils.copyStream(IOUtils.java:25)
	at com.aefyr.sai.shell.SuShell.execInternal(SuShell.java:73)
	at com.aefyr.sai.shell.SuShell.exec(SuShell.java:50)
	at com.aefyr.sai.installer.ShellSAIPackageInstaller.installApkFiles(ShellSAIPackageInstaller.java:82)
	at com.aefyr.sai.installer.SAIPackageInstaller.lambda$processQueue$0$SAIPackageInstaller(SAIPackageInstaller.java:90)
	at com.aefyr.sai.installer.-$$Lambda$SAIPackageInstaller$6hKMtxaB1Yqc0HYKOE26UUOnkTo.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
	Suppressed: java.io.IOException: Stream closed
		at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
		at java.io.OutputStream.write(OutputStream.java:116)
		at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
		at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
		at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
		at com.aefyr.sai.shell.SuShell.execInternal(SuShell.java:74)
		... 7 more
Caused by: android.system.ErrnoException: write failed: EPIPE (Broken pipe)
	at libcore.io.Linux.writeBytes(Native Method)
	at libcore.io.Linux.write(Linux.java:294)
	at libcore.io.ForwardingOs.write(ForwardingOs.java:241)
	at libcore.io.BlockGuardOs.write(BlockGuardOs.java:416)
	at libcore.io.ForwardingOs.write(ForwardingOs.java:241)
	at libcore.io.IoBridge.write(IoBridge.java:539)
	... 12 more

	at com.aefyr.sai.installer.ShellSAIPackageInstaller.ensureCommandSucceeded(ShellSAIPackageInstaller.java:100)
	at com.aefyr.sai.installer.ShellSAIPackageInstaller.installApkFiles(ShellSAIPackageInstaller.java:82)
	at com.aefyr.sai.installer.SAIPackageInstaller.lambda$processQueue$0$SAIPackageInstaller(SAIPackageInstaller.java:90)
	at com.aefyr.sai.installer.-$$Lambda$SAIPackageInstaller$6hKMtxaB1Yqc0HYKOE26UUOnkTo.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
``` 

## More Info
- Logcat : [sai-logcat-rooted-method-fails_20191016.txt](https://github.com/Aefyr/SAI/files/3733896/sai-logcat-rooted-method-fails_20191016.txt)
- Screenshot :
![Screenshot_20191016-181331](https://user-images.githubusercontent.com/16160401/66912964-a18d0600-f04e-11e9-9542-dee38125ca3c.png)

**Comment by Aefyr** [comment]
Enable "Extract APKs from archives" setting

**Comment by nooriro** [comment]
IT WORKED!!!
I have never thought that setting since '**Not recommended to enable**' notice in its description. :grin: 
Thank you for letting me know.

![Screenshot_20191016-202857](https://user-images.githubusercontent.com/16160401/66915340-bcae4480-f053-11e9-9140-0001bc6cc9eb.png)

![Screenshot_20191016-201638](https://user-images.githubusercontent.com/16160401/66915065-182c0280-f053-11e9-975e-5261c30b3ecf.png)

**Comment by Aefyr** [comment]
Yeah, it's made exactly for this error, in the next version there will be a suggestion to enable it instead of error
