### ISSUE TITLE
rootless installer error

### ISSUE THREAD

**Issue by Zspirates96** [Aefyr/SAI#46]
I got this error when trying to install an app: rhs == null. Help?
It works fine on my android pie device but not on my android 7.0 tablet

**Comment by Aefyr** [comment]
I have no idea what rhs == null means, is it the actual error log?

**Comment by Zspirates96** [comment]
yup, that is exactly what was shown.

**Comment by Aefyr** [comment]
Can you find the error in logcat and show stacktrace? I'll alos add displaying stacktrace in error dialog in the next version

**Comment by Zspirates96** [comment]
[logcat.txt](https://github.com/Aefyr/SAI/files/3774151/logcat.txt)
Im new to this so hopefully i get it this right

**Comment by Aefyr** [comment]
Sorry, this logcat is missing stacktrace, but I've just released a new version that displays a complete log on error, can you copy the error log from there?

**Comment by Zspirates96** [comment]
> Rootless installer error:

 java.lang.NullPointerException: rhs == null
	at android.os.Parcel.readException(Parcel.java:1689)
	at android.os.Parcel.readException(Parcel.java:1636)
	at android.content.pm.IPackageInstaller$Stub$Proxy.createSession(IPackageInstaller.java:249)
	at android.content.pm.PackageInstaller.createSession(PackageInstaller.java:297)
	at com.aefyr.sai.installer.rootless.RootlessSAIPackageInstaller.installApkFiles(RootlessSAIPackageInstaller.java:79)
	at com.aefyr.sai.installer.SAIPackageInstaller.lambda$processQueue$0$SAIPackageInstaller(SAIPackageInstaller.java:90)
	at com.aefyr.sai.installer.-$$Lambda$SAIPackageInstaller$6hKMtxaB1Yqc0HYKOE26UUOnkTo.run(lambda)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
<
Here is it

**Comment by Zspirates96** [comment]
Rootless installer error:

 java.lang.NullPointerException: rhs == null
	at android.os.Parcel.readException(Parcel.java:1689)
	at android.os.Parcel.readException(Parcel.java:1636)
	at android.content.pm.IPackageInstaller$Stub$Proxy.createSession(IPackageInstaller.java:249)
	at android.content.pm.PackageInstaller.createSession(PackageInstaller.java:297)
	at com.aefyr.sai.installer.rootless.RootlessSAIPackageInstaller.installApkFiles(RootlessSAIPackageInstaller.java:79)
	at com.aefyr.sai.installer.SAIPackageInstaller.lambda$processQueue$0$SAIPackageInstaller(SAIPackageInstaller.java:90)
	at com.aefyr.sai.installer.-$$Lambda$SAIPackageInstaller$6hKMtxaB1Yqc0HYKOE26UUOnkTo.run(lambda)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
Here is it

**Comment by Aefyr** [comment]
Ok, it looks like the error occurs in the system package installer service and it's not an error that may occur normally according to the docs, so I think you have a bad ROM. I suggest trying Rooted/Shizuku installer.

**Comment by Zspirates96** [comment]
Im stuck in asus rom coz they lock the bootloader and no root. Guess im doomed, thx anyway.

**Comment by Aefyr** [comment]
You can start Shizuku server using ADB

**Comment by Zspirates96** [comment]
Okay, i will try to work it out

**Comment by Zspirates96** [comment]
Apparently, life is lemon.
Here is another error using shizuku

Shizuku installer error:

 Device: asus ASUS_P00I | Not MIUI | Android 7.0 | Using ZipApkSource ApkSource implementation | SAI 2.9

java.lang.IllegalStateException: Unable to create session, attempted commands: 

1) ==========================
pm install-create -r --install-location 0 -i 'com.aefyr.sai'
VVVVVVVVVVVVVVVV
Command: pm install-create -r --install-location 0 -i 'com.aefyr.sai'
Exit code: 1
Out:

=============
Err:
Error: java.lang.NullPointerException: rhs == null

2) ==========================
pm install-create -r -i 'com.aefyr.sai'
VVVVVVVVVVVVVVVV
Command: pm install-create -r -i 'com.aefyr.sai'
Exit code: 1
Out:

=============
Err:
Error: java.lang.NullPointerException: rhs == null

	at com.aefyr.sai.installer.ShellSAIPackageInstaller.createSession(ShellSAIPackageInstaller.java:156)
	at com.aefyr.sai.installer.ShellSAIPackageInstaller.installApkFiles(ShellSAIPackageInstaller.java:79)
	at com.aefyr.sai.installer.SAIPackageInstaller.lambda$processQueue$0$SAIPackageInstaller(SAIPackageInstaller.java:90)
	at com.aefyr.sai.installer.-$$Lambda$SAIPackageInstaller$6hKMtxaB1Yqc0HYKOE26UUOnkTo.run(lambda)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

**Comment by Aefyr** [comment]
Same error, huh. Sorry, I don't think I can do anything to fix it then

**Comment by Zspirates96** [comment]
No prob

**Comment by Aefyr** [comment]
Closed because almost definitely a ROM issue

**Comment by drzraf** [comment]
on ASUS X008
```
java.lang.NullPointerException: rhs == null
	at android.os.Parcel.readException(Parcel.java:1689)
	at android.os.Parcel.readException(Parcel.java:1636)
	at android.content.pm.IPackageInstaller$Stub$Proxy.createSession(IPackageInstaller.java:249)
	at android.content.pm.PackageInstaller.createSession(PackageInstaller.java:297)
	at com.aefyr.sai.installer2.impl.rootless.RootlessSaiPackageInstaller.install(RootlessSaiPackageInstaller.java:85)
	at com.aefyr.sai.installer2.impl.rootless.RootlessSaiPackageInstaller.lambda$enqueueSession$0$RootlessSaiPackageInstaller(RootlessSaiPackageInstaller.java:67)
	at com.aefyr.sai.installer2.impl.rootless.-$$Lambda$RootlessSaiPackageInstaller$qjIAcEi1zRTbLvsC4Z-hfYgaI58.run(lambda)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
```

**Comment by waitxd** [comment]
Same issue with ASUS ZenFone 3 Laser (ZC551KL).

**Comment by jamoo502** [comment]
> Apparently, life is lemon. Here is another error using shizuku
> 
> Shizuku installer error:
> 
> Device: asus ASUS_P00I | Not MIUI | Android 7.0 | Using ZipApkSource ApkSource implementation | SAI 2.9
> 
> java.lang.IllegalStateException: Unable to create session, attempted commands:
> 
> 1. ==========================
>    pm install-create -r --install-location 0 -i 'com.aefyr.sai'
>    VVVVVVVVVVVVVVVV
>    Command: pm install-create -r --install-location 0 -i 'com.aefyr.sai'
>    Exit code: 1
>    Out:
> 
> ============= Err: Error: java.lang.NullPointerException: rhs == null
> 
> 2. ==========================
>    pm install-create -r -i 'com.aefyr.sai'
>    VVVVVVVVVVVVVVVV
>    Command: pm install-create -r -i 'com.aefyr.sai'
>    Exit code: 1
>    Out:
> 
> ============= Err: Error: java.lang.NullPointerException: rhs == null
> 
> ```
> at com.aefyr.sai.installer.ShellSAIPackageInstaller.createSession(ShellSAIPackageInstaller.java:156)
> at com.aefyr.sai.installer.ShellSAIPackageInstaller.installApkFiles(ShellSAIPackageInstaller.java:79)
> at com.aefyr.sai.installer.SAIPackageInstaller.lambda$processQueue$0$SAIPackageInstaller(SAIPackageInstaller.java:90)
> at com.aefyr.sai.installer.-$$Lambda$SAIPackageInstaller$6hKMtxaB1Yqc0HYKOE26UUOnkTo.run(lambda)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
> at java.lang.Thread.run(Thread.java:761)
> ```

java.lang.NullPointerException: rhs == null
	at android.os.Parcel.readException(Parcel.java:1689)
	at android.os.Parcel.readException(Parcel.java:1636)
	at android.content.pm.IPackageInstaller$Stub$Proxy.createSession(IPackageInstaller.java:249)
	at android.content.pm.PackageInstaller.createSession(PackageInstaller.java:297)
	at com.aefyr.sai.installer2.impl.rootless.RootlessSaiPackageInstaller.install(RootlessSaiPackageInstaller.java:85)
	at com.aefyr.sai.installer2.impl.rootless.RootlessSaiPackageInstaller.lambda$enqueueSession$0$RootlessSaiPackageInstaller(RootlessSaiPackageInstaller.java:67)
	at com.aefyr.sai.installer2.impl.rootless.-$$Lambda$RootlessSaiPackageInstaller$qjIAcEi1zRTbLvsC4Z-hfYgaI58.run(lambda)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
