### ISSUE TITLE
App Crash on apk installation

### ISSUE THREAD

**Issue by Tisckkytt** [Aefyr/SAI#47]
Issue: Can't install backed up apk in both root & rootless method. SAI crashes as soon as zip selected for installation.
Android version: 10 (PixelExperience)
Build version: 2.8 (From playstore)
 

`Stack trace:  
java.lang.IllegalStateException: Must Initialize Fabric before using singleton()
	at io.fabric.sdk.android.Fabric.singleton(Fabric.java:301)
	at io.fabric.sdk.android.Fabric.getKit(Fabric.java:551)
	at com.crashlytics.android.Crashlytics.getInstance(Crashlytics.java:191)
	at com.crashlytics.android.Crashlytics.checkInitialized(Crashlytics.java:390)
	at com.crashlytics.android.Crashlytics.log(Crashlytics.java:233)
	at com.aefyr.sai.utils.Logs.d(Logs.java:24)
	at com.aefyr.sai.utils.Logs.d(Logs.java:29)
	at com.aefyr.sai.installer.SAIPackageInstaller.dispatchCurrentSessionUpdate(SAIPackageInstaller.java:111)
	at com.aefyr.sai.installer.SAIPackageInstaller.processQueue(SAIPackageInstaller.java:88)
	at com.aefyr.sai.installer.SAIPackageInstaller.startInstallationSession(SAIPackageInstaller.java:73)
	at com.aefyr.sai.viewmodels.InstallerViewModel.installPackagesFromZip(InstallerViewModel.java:76)
	at com.aefyr.sai.ui.fragments.InstallerFragment.onFilesSelected(InstallerFragment.java:194)
	at com.aefyr.sai.ui.dialogs.FilePickerDialogFragment.lambda$onCreateDialog$0$FilePickerDialogFragment(FilePickerDialogFragment.java:98)
	at com.aefyr.sai.ui.dialogs.-$$Lambda$FilePickerDialogFragment$iMS6ujDR802nqbvMXbnWkhPMTWg.onSelectedFilePaths(Unknown Source:2)
	at com.github.angads25.filepicker.view.FilePickerDialog.finishSelection(FilePickerDialog.java:460)
	at com.github.angads25.filepicker.view.FilePickerDialog.access$200(FilePickerDialog.java:55)
	at com.github.angads25.filepicker.view.FilePickerDialog$1.onClick(FilePickerDialog.java:133)
	at android.view.View.performClick(View.java:7140)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:942)
	at android.view.View.performClickInternal(View.java:7117)
	at android.view.View.access$3500(View.java:801)
	at android.view.View$PerformClick.run(View.java:27351)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)`

**Comment by Tisckkytt** [comment]
Also, I get this from Scoop

FATAL EXCEPTION: main
Process: com.aefyr.sai, PID: 29168
java.lang.IllegalStateException: Must Initialize Fabric before using singleton()
	at io.fabric.sdk.android.Fabric.singleton(Fabric.java:301)
	at io.fabric.sdk.android.Fabric.getKit(Fabric.java:551)
	at com.crashlytics.android.Crashlytics.getInstance(Crashlytics.java:191)
	at com.crashlytics.android.Crashlytics.checkInitialized(Crashlytics.java:390)
	at com.crashlytics.android.Crashlytics.log(Crashlytics.java:233)
	at com.aefyr.sai.utils.Logs.d(Logs.java:24)
	at com.aefyr.sai.utils.Logs.d(Logs.java:29)
	at com.aefyr.sai.installer.SAIPackageInstaller.dispatchCurrentSessionUpdate(SAIPackageInstaller.java:111)
	at com.aefyr.sai.installer.SAIPackageInstaller.processQueue(SAIPackageInstaller.java:88)
	at com.aefyr.sai.installer.SAIPackageInstaller.startInstallationSession(SAIPackageInstaller.java:73)
	at com.aefyr.sai.viewmodels.InstallerViewModel.installPackagesFromZip(InstallerViewModel.java:76)
	at com.aefyr.sai.ui.fragments.InstallerFragment.onFilesSelected(InstallerFragment.java:194)
	at com.aefyr.sai.ui.dialogs.FilePickerDialogFragment.lambda$onCreateDialog$0$FilePickerDialogFragment(FilePickerDialogFragment.java:98)
	at com.aefyr.sai.ui.dialogs.-$$Lambda$FilePickerDialogFragment$iMS6ujDR802nqbvMXbnWkhPMTWg.onSelectedFilePaths(Unknown Source:2)
	at com.github.angads25.filepicker.view.FilePickerDialog.finishSelection(FilePickerDialog.java:460)
	at com.github.angads25.filepicker.view.FilePickerDialog.access$200(FilePickerDialog.java:55)
	at com.github.angads25.filepicker.view.FilePickerDialog$1.onClick(FilePickerDialog.java:133)
	at android.view.View.performClick(View.java:7140)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:942)
	at android.view.View.performClickInternal(View.java:7117)
	at android.view.View.access$3500(View.java:801)
	at android.view.View$PerformClick.run(View.java:27351)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by Aefyr** [comment]
I've seen this bug on some custom Q roms, I think it can be fixed by dirty flashing the same rom

**Comment by Tisckkytt** [comment]
After Dirty flashing ROM it didn't work but a clean installation of SAI seems to have fixed the issue for now. Sorry for not trying clean installation before reporting.
